export default {
  MAIN: '/',
  SIGNUP: '/signup',
  SIGNIN: '/signin',
  PROFILE: '/profile',
  CART: '/cart',
  MAC: '/shop/mac',
  IPHONE: '/shop/iphone',
  MACBOOK_AIR_BUY: '/shop/buy/macbook-air',
  MACBOOK_PRO_BUY: '/shop/buy/macbook-pro',
  IPHONE_BUY: '/shop/buy/iphone-14',
  IPHONE_PRO_BUY: '/shop/buy/iphone-14-pro',
  MAC_COMPARE: '/shop/compare/mac',
  IPHONE_COMPARE: '/shop/compare/iphone',
  MACBOOK_PRO_INTRO: '/shop/macbook-pro',
  MACBOOK_AIR_INTRO: '/shop/macbook-air',
  IPHONE_INTRO: '/shop/iphone-14',
  IPHONE_PRO_INTRO: '/shop/iphone-14-pro',
  COMMUNITY: '/community',
  COMMUNITY_CATEGORY_IPHONE: '/community/iphone',
  COMMUNITY_CATEGORY_MAC: '/community/mac',
  COMMUNITY_POST: '/community/:id',
  COMMUNITY_QUESTION: '/community/question',
  COMMUNITY_RANK: '/community/rank',
  COMMUNITY_ME: '/community/me',
};
