GET http://localhost:8000/api/profile/1

###

GET http://localhost:8000/api/post/1

###


GET http://localhost:8000/api/posts/1

###


GET http://localhost:8000/api/rank

###

GET  http://localhost:8000/api/auth

###


